# Generated by Django 3.0.8 on 2020-07-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citrys_scraping', '0002_auto_20200718_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='prise',
            new_name='price',
        ),
    ]
