# Generated by Django 3.0.8 on 2020-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citrys_scraping', '0003_auto_20200718_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
